‎
+3
Lines changed: 3 additions & 0 deletions
Original file line number	Diff line number	Diff line change
@@ -0,0 +1,3 @@
from django.contrib import admin
# Register your models here.
‎apps.py‎
+5
Lines changed: 5 additions & 0 deletions
Original file line number	Diff line number	Diff line change
@@ -0,0 +1,5 @@
from django.apps import AppConfig
class DsaappConfig(AppConfig):
    name = 'DSAAPP'
‎asgi.py‎
+16
Lines changed: 16 additions & 0 deletions
Original file line number	Diff line number	Diff line change
@@ -0,0 +1,16 @@
"""
ASGI config for DSA project.
It exposes the ASGI callable as a module-level variable named ``application``.
For more information on this file, see
https://docs.djangoproject.com/en/6.0/howto/deployment/asgi/
"""
import os
from django.core.asgi import get_asgi_application
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'DSA.settings')
application = get_asgi_application()
‎models.py‎
+3
Lines changed: 3 additions & 0 deletions
Original file line number	Diff line number	Diff line change
@@ -0,0 +1,3 @@
from django.db import models
# Create your models here.
‎settings.py‎
+118
Lines changed: 118 additions & 0 deletions
Original file line number	Diff line number	Diff line change
@@ -0,0 +1,118 @@
"""
Django settings for DSA project.
Generated by 'django-admin startproject' using Django 6.0.3.
For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iy)-aae&x^_$vgnq0)dl@m)tz$f)6cm(bj2)qe(=%x*@j@=)6*'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'DSA.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'DSA.wsgi.application'
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'
‎tests.py‎
+3
Lines changed: 3 additions & 0 deletions
Original file line number	Diff line number	Diff line change
@@ -0,0 +1,3 @@
from django.test import TestCase
# Create your tests here.
‎urls.py‎
+8
Lines changed: 8 additions & 0 deletions
Original file line number	Diff line number	Diff line change
@@ -0,0 +1,8 @@
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('djangoapp.urls'))
]
‎views.py‎
+10
Lines changed: 10 additions & 0 deletions
Original file line number	Diff line number	Diff line change
@@ -0,0 +1,10 @@
from django.shortcuts import render
from django.http import HttpResponse
def index(request):
    return render(request, 'SocialGraph.html')
def elevator(request):
    return render(request, 'Elevator.html')
‎wsgi.py‎
+16
Lines changed: 16 additions & 0 deletions
Original file line number	Diff line number	Diff line change
@@ -0,0 +1,16 @@
"""
WSGI config for DSA project.
It exposes the WSGI callable as a module-level variable named ``application``.
For more information on this file, see
https://docs.djangoproject.com/en/6.0/howto/deployment/wsgi/
"""
import os
from django.core.wsgi import get_wsgi_application
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'DSA.settings')
application = get_wsgi_application()
